export const SET_EDUCATIONS = "EDUCATIONS/SET_EDUCATIONS";
export const SET_EDUCATION_DETAIL = "EDUCATION/SET_EDUCATION_DETAIL";
export const SET_LOADING_FETCH = "LOADING/SET_LOADING_FETCH";
export const SET_ERROR = "ERROR/SET_ERROR";
