export const SET_COMMUNITIES = "COMMUNITIES/SET_COMMUNITIES";
export const SET_COMMUNITY_DETAIL = "COMMUNITY/SET_COMMUNITY_DETAIL";
export const SET_LOADING_FETCH = "LOADING/SET_LOADING_FETCH";
export const SET_ERROR = "ERROR/SET_ERROR";
