export const SET_COMPANIES = "COMPANIES/SET_COMPANIES";
export const SET_COMPANY_DETAIL = "COMPANY/SET_COMPANY_DETAIL";
export const SET_LOADING_FETCH = "LOADING/SET_LOADING_FETCH";
export const SET_ERROR = "ERROR/SET_ERROR";
